version: '3'
services:
    mep:
        container_name: mec_mep
        build: .
        image: mec/mep
        expose:
            - 12345
        ports:
            - 12345:12345
        tty: true
        stdin_open: true
        networks:
            - edge-network
networks:
    edge-network:
        driver: bridge
